// src/features/counter/counterSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the counter
const initialState = {
  value: 0,
};

// Create a slice of the store
const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Export the reducer to be included in the store
export default counterSlice.reducer;
